import os

MORIARTY_BRIDGE_NAME_ENV = "MORIARTY_BRIDGE_NAME"
MORIARTY_MATRIX_TOKEN_ENV = "MORIARTY_MATRIX_TOKEN"
MORIARTY_CONNECTOR_ENDPOINT_ENV = "MORIARTY_CONNECTOR_ENDPOINT"
MORIARTY_BRIDGE_RESULT_QUEUE_URL_ENV = "MORIARTY_BRIDGE_RESULT_QUEUE_URL"


def get_bridge_name() -> str:
    return os.getenv(MORIARTY_BRIDGE_NAME_ENV, "sqs")


def get_bridge_result_queue_url() -> str:
    return os.getenv(MORIARTY_BRIDGE_RESULT_QUEUE_URL_ENV, "")
