apiVersion: v1
kind: Service
metadata:
  name: postgres-node
  namespace: moriarty
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31432
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: moriarty
spec:
  selector:
    app: postgres
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: moriarty
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: VGgxczFzTXlQYXNzdzByZA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: moriarty
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: moriarty-matrix
          envFrom:
            - secretRef:
                name: database
          ports:
            - containerPort: 5432
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "sh",
                    "-c",
                    "while ! pg_isready -U postgres; do sleep 1; done",
                  ]
