apiVersion: v1
kind: Service
metadata:
  name: moriarty-operator
  namespace: moriarty
spec:
  selector:
    app: moriarty-operator
  ports:
    - name: moriarty-operator
      port: 8902
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moriarty-operator-api
  namespace: moriarty
  labels:
    app: moriarty-operator-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: moriarty-operator-api
  template:
    metadata:
      labels:
        app: moriarty-operator-api
    spec:
      containers:
        - name: moriarty-operator-api
          image: wh1isper/moriarty
          command: ["moriarty-operator"]
          args: ["api"]
          envFrom:
            - secretRef:
                name: sqs-bridge
            - secretRef:
                name: redis
            - secretRef:
                name: database
            - secretRef:
                name: model
            - configMapRef:
                name: kubespawner
          ports:
            - containerPort: 8902
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8902
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 20
      restartPolicy: Always
