---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: moriarty-operator
  namespace: moriarty
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: moriarty-operator
  namespace: moriarty
rules:
  # FIXME: authorization on demand
  - apiGroups: ["*"]
    resources: ["*"]
    resourceNames: []
    verbs: ["*"]
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: moriarty-operator
  namespace: moriarty
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: moriarty-operator
subjects:
  - kind: ServiceAccount
    name: moriarty-operator
    namespace: moriarty
