apiVersion: v1
kind: Service
metadata:
  name: moriarty-connector
  namespace: moriarty
spec:
  selector:
    app: moriarty-connector
  ports:
    - name: moriarty-connector
      port: 8901
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: moriarty-connector
  namespace: moriarty
  labels:
    app: moriarty-connector
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: moriarty-connector
  template:
    metadata:
      labels:
        app: moriarty-connector
    spec:
      containers:
        - name: moriarty-connector
          image: wh1isper/moriarty
          command: ["moriarty-connector"]
          args: ["start"]
          envFrom:
            - secretRef:
                name: sqs-bridge
          ports:
            - containerPort: 8901
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8901
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 20
      restartPolicy: Always
